name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: santhoshkaleru
          password: dckr_pat_SXdYQAIX2tnMx9ycobhmiY41AM0
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: santhoshkaleru/santhosh_devops_ui:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 54.145.81.145
          username: ${{ secrets.EC2_USERNAME }}
          key: |
              -----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
              QyNTUxOQAAACDV9QQvtPTiOELeQB/SHRclFzEOK4obbF59GQBse2lH6gAAAKAFR0K4BUdC
              uAAAAAtzc2gtZWQyNTUxOQAAACDV9QQvtPTiOELeQB/SHRclFzEOK4obbF59GQBse2lH6g
              AAAEAk6SgYYTPlmsPomb8cAaZQvNGIsV9PeUcDHIrU/4lCzNX1BC+09OI4Qt5AH9IdFyUX
              MQ4rihtsXn0ZAGx7aUfqAAAAF3VidW50dUBpcC0xNzItMzEtMjQtMjM5AQIDBAUG
              -----END OPENSSH PRIVATE KEY-----
          script: |
            # Pull the latest image
            docker pull santhoshkaleru/santhosh_devops_ui:latest
            # Stop and remove the old container if it exists
            docker stop demo3 || true
            docker rm demo3 || true
            # Run the new container
            docker run -d -p 80:80 --name demo3 --restart always santhoshkaleru/santhosh_devops_ui:latest